version: "3.9"
services:

  nginx-proxy:
    image: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9201:9201"
    networks:
      es-net:
        ipv4_address: 172.20.0.6

  port-forward:
    image: "bitnami/kubectl"
    volumes:
      - ~/.kube/config:/.kube/config
    ports:
      - "9200:9200"
    command: port-forward -n elasticsearch svc/elasticsearch-master 9200 --address localhost,172.20.0.5
    networks:
      es-net:
        ipv4_address: 172.20.0.5

networks:
  es-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
